site_name: ""
site_url: https://gonka.ai/
edit_uri: ""
site_description: >-
  Learn to configure and use Gonka network

# Content
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Developer:
    - Quickstart: developer/quickstart.md
    - Details: developer/details.md
  - Host:
    - Quickstart: host/quickstart.md
    - Benchmark to choose optimal deployment config for LLMs: host/benchmark-to-choose-optimal-deployment-config-for-llms.md
    - Genesis: host/genesis.md
    - Hardware specifications: host/hardware-specifications.md
    - How to edit Host public info: host/host_info.md
    - Key management: host/key-management.md
    - MLNode Management: host/mlnode-management.md
    - Multiple nodes: host/multiple-nodes.md
    - Network Node API: host/network-node-api.md
  - Wallet:
    - Dashboard: wallet/dashboard.md
    - Wallet & transfer guide: wallet/wallet-and-transfer-guide.md
    - Pricing: wallet/pricing.md
  - Model licenses: model-licenses.md
  - Transactions & governance: transactions-and-governance.md
  - Software upgrades: software-upgrades.md
  - Help:
    - FAQ: FAQ.md
    - Errors: Errors.md
    - Get help: help.md

# Visual
theme:
  name: material
  favicon: images/01-favicon.png
  logo: images/logos/gonka.svg
  custom_dir: overrides
  font:
    text: Manrope
  palette:
    # Light mode
    # media: "(prefers-color-scheme: light)"
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  include_search_page: false
  language: en
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.tracking
    - search.suggest

markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - toc
  # https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css
  - stylesheets/nft-landing.css

extra_javascript:
  - assets/javascripts/links.js
  - assets/javascripts/quickstart-configurator.js

plugins:
  - minify:
      minify_html: false
  - search:
      separator: '[\\s-]+'
      lang:
        - en
        - zh
  - mkdocs-video:
      is_video: true
      video_muted: true
      video_controls: true
      css_style:
        width: "50%"
  - i18n:
      reconfigure_material: true
      docs_structure: folder
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: zh
          name: 中文
          build: true
          nav_translations:
            Home: 首页
            Introduction: 介绍
            Developer: 开发者
            Quickstart: 快速上手
            Details: 细节
            Host: 节点
            "Multiple nodes": 多节点
            "Network Node API": 网络节点 API
            "MLNode Management": ML节点管理
            Key Management: 密钥管理
            Benchmark to Choose Optimal Deployment Config for LLMs: LLM 部署配置基准
            "Hardware Specifications": 硬件规格
            Genesis: 创世
            How to edit validator public info: 如何编辑验证者的公开信息
            SSL setup: SSL 设置
            Wallet: 钱包
            Dashboard: 仪表盘
            Wallet & Transfer Guide: 钱包与转账指南
            Pricing: 价格
            "Model licenses": 模型许可
            Transactions & Governance: 交易与治理
            Software Upgrades: 软件升级
            Help: 帮助
            FAQ: 常见问题
            Errors: 错误
            "Get help": 获取支持

strict: true

validation:
  links:
    absolute_links: ignore

extra:
  analytics:
    provider: google
    property: G-JWVG5X6CY5
